# Generated by Django 5.2 on 2025-04-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                ("badge", models.CharField(default=None, max_length=10)),
                ("title", models.CharField(default=None, max_length=50)),
                ("img", models.ImageField(upload_to="")),
                ("description", models.CharField(default=None, max_length=150)),
                ("dept", models.CharField(default=None, max_length=30)),
                ("courses", models.IntegerField(default=None, max_length=2)),
                ("rating", models.IntegerField(default=None, max_length=2)),
                ("paper", models.IntegerField(default=None, max_length=3)),
            ],
        ),
    ]
