# Generated by Django 5.2 on 2025-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students_records",
            name="address",
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name="students_records",
            name="contact",
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="course",
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="id",
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="name",
            field=models.CharField(blank=True, default=True, max_length=15),
        ),
    ]
