# Generated by Django 5.2 on 2025-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_students_records_address_students_records_contact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students_records",
            name="contact",
            field=models.IntegerField(default=True, max_length=10),
        ),
    ]
