# Generated by Django 5.2 on 2025-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_students_records_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students_records",
            name="address",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="contact",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="course",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="id",
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
