# Generated by Django 5.2 on 2025-04-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_students_records_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students_records",
            old_name="id",
            new_name="stu_id",
        ),
        migrations.AlterField(
            model_name="students_records",
            name="contact",
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
