# Generated by Django 5.2 on 2025-04-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_rename_id_students_records_stu_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="students_records",
            name="roll",
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
