# Generated by Django 5.2 on 2025-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_alter_students_records_roll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students_records",
            name="roll",
        ),
        migrations.AlterField(
            model_name="students_records",
            name="contact",
            field=models.CharField(default=None, max_length=10),
        ),
    ]
