# Generated by Django 5.2 on 2025-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0008_remove_students_records_roll_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="students_records",
            name="email",
            field=models.EmailField(default=None, max_length=255),
        ),
    ]
