# Generated by Django 5.2 on 2025-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_students_records_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="students_records",
            name="branch",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="students_records",
            name="fee_status",
            field=models.CharField(default="Paid", max_length=10),
        ),
        migrations.AddField(
            model_name="students_records",
            name="year",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="contact",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="course",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="students_records",
            name="stu_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
