# Generated by Django 5.2 on 2025-04-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student",
            "0010_students_records_branch_students_records_fee_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="students_records",
            name="fee_paid",
            field=models.IntegerField(default=None, max_length=9),
        ),
        migrations.AddField(
            model_name="students_records",
            name="fee_total",
            field=models.IntegerField(default=80000, max_length=9),
        ),
    ]
