# Generated by Django 5.2 on 2025-04-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_students_records_fee_paid_students_records_fee_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students_records",
            name="fee_total",
            field=models.IntegerField(default=80000),
        ),
    ]
