# Generated by Django 5.2 on 2025-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0018_alter_students_records_fee_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="students_records",
            name="pending_fee",
            field=models.IntegerField(default=0),
        ),
    ]
